# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 474)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.tx_username = QtWidgets.QLineEdit(self.groupBox)
        self.tx_username.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_username.setObjectName("tx_username")
        self.horizontalLayout_5.addWidget(self.tx_username)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.tx_password = QtWidgets.QLineEdit(self.groupBox)
        self.tx_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tx_password.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_password.setObjectName("tx_password")
        self.horizontalLayout_5.addWidget(self.tx_password)
        self.btn_login = QtWidgets.QPushButton(self.groupBox)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_5.addWidget(self.btn_login)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.horizontalLayout_12.setStretch(0, 5)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.sel_begindate = QtWidgets.QDateEdit(self.groupBox_2)
        self.sel_begindate.setAlignment(QtCore.Qt.AlignCenter)
        self.sel_begindate.setCalendarPopup(True)
        self.sel_begindate.setObjectName("sel_begindate")
        self.horizontalLayout_13.addWidget(self.sel_begindate)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.sel_enddate = QtWidgets.QDateEdit(self.groupBox_2)
        self.sel_enddate.setAlignment(QtCore.Qt.AlignCenter)
        self.sel_enddate.setCalendarPopup(True)
        self.sel_enddate.setObjectName("sel_enddate")
        self.horizontalLayout_13.addWidget(self.sel_enddate)
        self.horizontalLayout_13.setStretch(0, 2)
        self.horizontalLayout_13.setStretch(1, 3)
        self.horizontalLayout_13.setStretch(2, 2)
        self.horizontalLayout_13.setStretch(3, 3)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10.setStretch(0, 5)
        self.horizontalLayout_10.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.tx_hy_code = QtWidgets.QLineEdit(self.groupBox_3)
        self.tx_hy_code.setWhatsThis("")
        self.tx_hy_code.setObjectName("tx_hy_code")
        self.horizontalLayout_14.addWidget(self.tx_hy_code)
        self.horizontalLayout_14.setStretch(0, 2)
        self.horizontalLayout_14.setStretch(1, 8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.sel_hy_status = QtWidgets.QComboBox(self.groupBox_3)
        self.sel_hy_status.setModelColumn(0)
        self.sel_hy_status.setObjectName("sel_hy_status")
        self.sel_hy_status.addItem("")
        self.sel_hy_status.addItem("")
        self.sel_hy_status.addItem("")
        self.sel_hy_status.addItem("")
        self.sel_hy_status.addItem("")
        self.horizontalLayout_15.addWidget(self.sel_hy_status)
        self.btn_hy_imp = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_hy_imp.setObjectName("btn_hy_imp")
        self.horizontalLayout_15.addWidget(self.btn_hy_imp)
        self.horizontalLayout_15.setStretch(0, 2)
        self.horizontalLayout_15.setStretch(1, 6)
        self.horizontalLayout_15.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 5)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.tx_hd_code = QtWidgets.QLineEdit(self.groupBox_4)
        self.tx_hd_code.setObjectName("tx_hd_code")
        self.horizontalLayout_16.addWidget(self.tx_hd_code)
        self.btn_hd_find = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_hd_find.setObjectName("btn_hd_find")
        self.horizontalLayout_16.addWidget(self.btn_hd_find)
        self.horizontalLayout_16.setStretch(0, 2)
        self.horizontalLayout_16.setStretch(1, 6)
        self.horizontalLayout_16.setStretch(2, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        self.sel_hd_status = QtWidgets.QComboBox(self.groupBox_4)
        self.sel_hd_status.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.sel_hd_status.setObjectName("sel_hd_status")
        self.sel_hd_status.addItem("")
        self.sel_hd_status.addItem("")
        self.horizontalLayout_17.addWidget(self.sel_hd_status)
        self.btn_hd_imp = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_hd_imp.setObjectName("btn_hd_imp")
        self.horizontalLayout_17.addWidget(self.btn_hd_imp)
        self.horizontalLayout_17.setStretch(0, 2)
        self.horizontalLayout_17.setStretch(1, 6)
        self.horizontalLayout_17.setStretch(2, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 5)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.setStretch(0, 5)
        self.horizontalLayout_7.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.sel_store_vaild_status = QtWidgets.QComboBox(self.groupBox_6)
        self.sel_store_vaild_status.setAcceptDrops(False)
        self.sel_store_vaild_status.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.sel_store_vaild_status.setObjectName("sel_store_vaild_status")
        self.sel_store_vaild_status.addItem("")
        self.sel_store_vaild_status.addItem("")
        self.sel_store_vaild_status.addItem("")
        self.sel_store_vaild_status.addItem("")
        self.horizontalLayout_18.addWidget(self.sel_store_vaild_status)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_18.addWidget(self.label_9)
        self.sel_store_balance_status = QtWidgets.QComboBox(self.groupBox_6)
        self.sel_store_balance_status.setObjectName("sel_store_balance_status")
        self.sel_store_balance_status.addItem("")
        self.sel_store_balance_status.addItem("")
        self.sel_store_balance_status.addItem("")
        self.horizontalLayout_18.addWidget(self.sel_store_balance_status)
        self.horizontalLayout_18.setStretch(0, 2)
        self.horizontalLayout_18.setStretch(1, 3)
        self.horizontalLayout_18.setStretch(2, 2)
        self.horizontalLayout_18.setStretch(3, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_19.addWidget(self.label_11)
        self.sel_store_type = QtWidgets.QComboBox(self.groupBox_6)
        self.sel_store_type.setAutoFillBackground(False)
        self.sel_store_type.setEditable(False)
        self.sel_store_type.setMaxVisibleItems(10)
        self.sel_store_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.sel_store_type.setObjectName("sel_store_type")
        self.sel_store_type.addItem("")
        self.sel_store_type.addItem("")
        self.horizontalLayout_19.addWidget(self.sel_store_type)
        self.btn_store_imp = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_store_imp.setObjectName("btn_store_imp")
        self.horizontalLayout_19.addWidget(self.btn_store_imp)
        self.horizontalLayout_19.setStretch(0, 2)
        self.horizontalLayout_19.setStretch(1, 6)
        self.horizontalLayout_19.setStretch(2, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_21.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rb_hx_type_max = QtWidgets.QRadioButton(self.groupBox_7)
        self.rb_hx_type_max.setObjectName("rb_hx_type_max")
        self.verticalLayout_6.addWidget(self.rb_hx_type_max, 0, QtCore.Qt.AlignHCenter)
        self.rb_hx_type_real = QtWidgets.QRadioButton(self.groupBox_7)
        self.rb_hx_type_real.setObjectName("rb_hx_type_real")
        self.verticalLayout_6.addWidget(self.rb_hx_type_real, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_21.addLayout(self.verticalLayout_6)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.tx_hx_grp1_name = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_hx_grp1_name.sizePolicy().hasHeightForWidth())
        self.tx_hx_grp1_name.setSizePolicy(sizePolicy)
        self.tx_hx_grp1_name.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_hx_grp1_name.setObjectName("tx_hx_grp1_name")
        self.verticalLayout_9.addWidget(self.tx_hx_grp1_name)
        self.tx_hx_grp2_name = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_hx_grp2_name.sizePolicy().hasHeightForWidth())
        self.tx_hx_grp2_name.setSizePolicy(sizePolicy)
        self.tx_hx_grp2_name.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_hx_grp2_name.setObjectName("tx_hx_grp2_name")
        self.verticalLayout_9.addWidget(self.tx_hx_grp2_name)
        self.verticalLayout_9.setStretch(0, 3)
        self.verticalLayout_9.setStretch(1, 3)
        self.verticalLayout_9.setStretch(2, 3)
        self.horizontalLayout_22.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.tx_hx_grp1_max = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_hx_grp1_max.sizePolicy().hasHeightForWidth())
        self.tx_hx_grp1_max.setSizePolicy(sizePolicy)
        self.tx_hx_grp1_max.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_hx_grp1_max.setObjectName("tx_hx_grp1_max")
        self.verticalLayout_8.addWidget(self.tx_hx_grp1_max)
        self.tx_hx_grp2_max = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_hx_grp2_max.sizePolicy().hasHeightForWidth())
        self.tx_hx_grp2_max.setSizePolicy(sizePolicy)
        self.tx_hx_grp2_max.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_hx_grp2_max.setObjectName("tx_hx_grp2_max")
        self.verticalLayout_8.addWidget(self.tx_hx_grp2_max)
        self.verticalLayout_8.setStretch(0, 3)
        self.verticalLayout_8.setStretch(1, 3)
        self.verticalLayout_8.setStretch(2, 3)
        self.horizontalLayout_22.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.tx_hx_grp1_codelist = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_hx_grp1_codelist.sizePolicy().hasHeightForWidth())
        self.tx_hx_grp1_codelist.setSizePolicy(sizePolicy)
        self.tx_hx_grp1_codelist.setObjectName("tx_hx_grp1_codelist")
        self.verticalLayout_7.addWidget(self.tx_hx_grp1_codelist)
        self.tx_hx_grp2_codelist = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_hx_grp2_codelist.sizePolicy().hasHeightForWidth())
        self.tx_hx_grp2_codelist.setSizePolicy(sizePolicy)
        self.tx_hx_grp2_codelist.setObjectName("tx_hx_grp2_codelist")
        self.verticalLayout_7.addWidget(self.tx_hx_grp2_codelist)
        self.verticalLayout_7.setStretch(0, 3)
        self.verticalLayout_7.setStretch(1, 3)
        self.verticalLayout_7.setStretch(2, 3)
        self.horizontalLayout_22.addLayout(self.verticalLayout_7)
        self.horizontalLayout_22.setStretch(0, 2)
        self.horizontalLayout_22.setStretch(1, 2)
        self.horizontalLayout_22.setStretch(2, 6)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btn_hx_find = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_hx_find.setObjectName("btn_hx_find")
        self.horizontalLayout_20.addWidget(self.btn_hx_find)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21.setStretch(0, 2)
        self.horizontalLayout_21.setStretch(1, 7)
        self.horizontalLayout_21.setStretch(2, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.setStretch(3, 3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.stb_info = QtWidgets.QStatusBar(MainWindow)
        self.stb_info.setObjectName("stb_info")
        MainWindow.setStatusBar(self.stb_info)

        self.retranslateUi(MainWindow)
        self.sel_store_type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "系统登陆"))
        self.label.setText(_translate("MainWindow", "用户名"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        self.btn_login.setText(_translate("MainWindow", "登陆"))
        self.groupBox_2.setTitle(_translate("MainWindow", "查询时间选择"))
        self.label_3.setText(_translate("MainWindow", "起始时间"))
        self.label_4.setText(_translate("MainWindow", "结束时间"))
        self.groupBox_3.setTitle(_translate("MainWindow", "会员信息导出"))
        self.label_5.setText(_translate("MainWindow", "券码ID"))
        self.label_6.setText(_translate("MainWindow", "券码状态"))
        self.sel_hy_status.setItemText(0, _translate("MainWindow", "未使用"))
        self.sel_hy_status.setItemText(1, _translate("MainWindow", "已使用"))
        self.sel_hy_status.setItemText(2, _translate("MainWindow", "已过期"))
        self.sel_hy_status.setItemText(3, _translate("MainWindow", "已作废"))
        self.sel_hy_status.setItemText(4, _translate("MainWindow", "全部"))
        self.btn_hy_imp.setText(_translate("MainWindow", "导出"))
        self.groupBox_4.setTitle(_translate("MainWindow", "活动信息查询"))
        self.label_7.setText(_translate("MainWindow", "活动ID"))
        self.btn_hd_find.setText(_translate("MainWindow", "查询"))
        self.label_8.setText(_translate("MainWindow", "发放状态"))
        self.sel_hd_status.setItemText(0, _translate("MainWindow", "发放成功"))
        self.sel_hd_status.setItemText(1, _translate("MainWindow", "全部"))
        self.btn_hd_imp.setText(_translate("MainWindow", "导出"))
        self.groupBox_5.setTitle(_translate("MainWindow", "交易明细查询"))
        self.groupBox_6.setTitle(_translate("MainWindow", "门店信息查询"))
        self.label_10.setText(_translate("MainWindow", "门店状态"))
        self.sel_store_vaild_status.setItemText(0, _translate("MainWindow", "不限"))
        self.sel_store_vaild_status.setItemText(1, _translate("MainWindow", "已生效"))
        self.sel_store_vaild_status.setItemText(2, _translate("MainWindow", "已失效"))
        self.sel_store_vaild_status.setItemText(3, _translate("MainWindow", "已废止"))
        self.label_9.setText(_translate("MainWindow", "结算类型"))
        self.sel_store_balance_status.setItemText(0, _translate("MainWindow", "不限"))
        self.sel_store_balance_status.setItemText(1, _translate("MainWindow", "可结算"))
        self.sel_store_balance_status.setItemText(2, _translate("MainWindow", "不可结算"))
        self.label_11.setText(_translate("MainWindow", "门店类型"))
        self.sel_store_type.setCurrentText(_translate("MainWindow", "门店列表"))
        self.sel_store_type.setItemText(0, _translate("MainWindow", "门店列表"))
        self.sel_store_type.setItemText(1, _translate("MainWindow", "买单列表"))
        self.btn_store_imp.setText(_translate("MainWindow", "导出"))
        self.groupBox_7.setTitle(_translate("MainWindow", "券码领取-核销查询统计"))
        self.rb_hx_type_max.setText(_translate("MainWindow", "按最大领取数计算"))
        self.rb_hx_type_real.setText(_translate("MainWindow", "按实际领取数计算"))
        self.label_12.setText(_translate("MainWindow", "券组名称"))
        self.label_13.setText(_translate("MainWindow", "券组最大发券量"))
        self.label_14.setText(_translate("MainWindow", "券组列表"))
        self.btn_hx_find.setText(_translate("MainWindow", "查询"))
